[formatter.nix]
command = "alejandra"
includes = ["*.nix"]
excludes = [
  "overrides/nodejs/electron/*",
  "src/templates/translators/*",
  "src/modules/_template/*",
  "src/modules/utils/poetry2nix/semver.nix",
]

[formatter.py]
command = "black"
includes = ["*.py"]
